---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
list.of.packages <- c("dplyr", "ggplot2", "knitr")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)>0) {install.packages(new.packages)} 
require(dplyr)
require(ggplot2)
require(knitr)
setwd("G://Documents//GitHub//RepData_PeerAssessment1")
## Loading and preprocessing the data
```{r}
unzip("activity.zip")
rawactivities<-read.csv("activity.csv")
rawactivities$date<-as.Date(rawactivities$date)
str(rawactivities)
```
## What is mean total number of steps taken per day?
For this part of the assignment, you can ignore the missing values in the dataset.
```{r}
#activities<-filter(rawactivities, complete.cases(rawactivities))
activities<-na.omit(rawactivities)
str(activities)
length(activities$steps)
```
#Calculate the total number of steps taken per day
```{r}
#stepsperday <- aggregate(steps ~ date, data = activities, FUN = sum)
#length(activities$steps)

```